### ISSUE TITLE
I wish the reverse could be done

### ISSUE THREAD

**Issue by KatkayApps** [Julius-Bendt/homebridge-dummyswitch-webhook#2]
to create a dummy switch that could be set on or off by webhooks...

**Comment by Julius-Bendt** [comment]
Hi Katkay,

as far as I know, Homebridge doesn't expose any of the services (such as the switch). This means that an all around solution will be hard to create.

I would recommend you to fork this project and fetch data from some other api (that could be running on the same server as homebridge) which the plugin hereafter can fetch data from. Let me know if you need help

**Comment by KatkayApps** [comment]
thanks!
